language: php

git:
  depth: 1

cache:
  directories:
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"

php:
- 5.6

install:
- composer install

script:
- composer grumphp

after_success:
- phpenv config-rm xdebug.ini
- composer scrutinizer
